title: Matt Chapman # your name (or website title) here
logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  MSc student studying Data Science and Applied Machine Learning at Oxford University. Particularly interested in NLP, geospatial analytics and interpretable ML.
  <br><br>
  3+ years of commercial experience in analytics, strategy and sales. Previously at Vodafone, VIMA Group (management consulting), Ovo Energy, HSBC.
  <br><br>
  Ranked in top 10% of undergraduate cohort at Cambridge University.
  <br><br>
  <a href="https://www.linkedin.com/in/matt-chapman-ba8488118/">View my LinkedIn Profile</a> 
  <br><br>
  <a href="/pdf/Matt_Chapman_CV.pdf">View my CV</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
